# Use the .NET 8.0 SDK image to build the solution
FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
WORKDIR /src

# Expose the application port
EXPOSE 9999

# Copy csproj files and restore as distinct layers to cache restored packages
COPY ["appLngApi/appLngApi.csproj", "appLngApi/"]
COPY ["Core/Core.csproj", "Core/"]
COPY ["MySQLRepo/MySQLRepo.csproj", "MySQLRepo/"]
COPY ["UserRegistry/UserRegistry.csproj", "UserRegistry/"]
RUN dotnet restore "appLngApi/appLngApi.csproj"

# Copy the rest of the source code
COPY . .

# Build and publish the application
RUN dotnet publish "appLngApi/appLngApi.csproj" -c Release -o /app/publish -v detailed

# Use the ASP.NET Core runtime image for the final image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS final
WORKDIR /app
COPY --from=build /app/publish .
ENTRYPOINT ["dotnet", "appLngApi.dll"]
