name: DeployFrontend
on:
  push:
    branches:
      - master
    paths:
      - 'frontend/**'
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build -t kalinared/lng2front:latest ./frontend

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_ACCESS_TOKEN }}
          
      - name: Push Docker image to Docker Hub
        run: docker push kalinared/lng2front:latest
        
      - name: Deploy to Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          password: ${{ secrets.SERVER_PASSWORD }}
          script: |
            docker stop $(docker ps -q --filter ancestor=kalinared/lng2front:latest) || true
            docker rmi kalinared/lng2front:latest
            docker pull kalinared/lng2front:latest
            docker run --rm --name lng2front-container -d -p 80:80 --network my-network kalinared/lng2front